services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-hackathon-backend-prod
    ports:
      - "8002:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    networks:
      - ai-hackathon-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-hackathon-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ai-hackathon-network
    restart: unless-stopped

networks:
  ai-hackathon-network:
    driver: bridge
