# ==========================================
# GCP環境用のdocker-compose設定
# ==========================================
version: '3.8'

services:
  backend:
    volumes:
      # Google Cloud Filestore（NFSベース）を使用
      - type: volume
        source: backend-sessions
        target: /app/tmp/user_sessions
        volume:
          nocopy: true
      - type: volume
        source: backend-logs
        target: /app/logs
        volume:
          nocopy: true

  adk:
    volumes:
      - ./backend:/app
      - type: volume
        source: backend-sessions
        target: /app/tmp/user_sessions
        volume:
          nocopy: true
      - type: volume
        source: backend-logs
        target: /app/logs
        volume:
          nocopy: true

volumes:
  backend-sessions:
    driver: local
    driver_opts:
      type: nfs
      # Google Cloud Filestore のIPアドレス
      o: "addr=10.0.0.2,nfsvers=3"
      device: ":/sessions"

  backend-logs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=10.0.0.2,nfsvers=3"
      device: ":/logs"
