# ==========================================
# AWS環境用のdocker-compose設定
# ==========================================
version: '3.8'

services:
  backend:
    # ... 既存の設定 ...
    volumes:
      # AWS EFS（Elastic File System）を使用
      - type: volume
        source: backend-sessions
        target: /app/tmp/user_sessions
        volume:
          nocopy: true
      - type: volume
        source: backend-logs
        target: /app/logs
        volume:
          nocopy: true

  adk:
    # ... 既存の設定 ...
    volumes:
      - ./backend:/app
      # 同じEFSボリュームを共有
      - type: volume
        source: backend-sessions
        target: /app/tmp/user_sessions
        volume:
          nocopy: true
      - type: volume
        source: backend-logs
        target: /app/logs
        volume:
          nocopy: true

volumes:
  backend-sessions:
    driver: local
    driver_opts:
      type: nfs
      # AWS EFSのマウントポイント
      o: "addr=fs-xxxxx.efs.ap-northeast-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      device: ":/sessions"

  backend-logs:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=fs-xxxxx.efs.ap-northeast-1.amazonaws.com,nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2"
      device: ":/logs"
